### ISSUE TITLE
Add contributors/maintainers?

### ISSUE THREAD

**Issue by alecthomas** [go-gorp/gorp#211]
Hi,

Firstly, thanks for Gorp, it really is a nice, elegant, idiomatic SQL abstraction layer for Go.

For whatever reason, insufficient time, life, etc. it appears that gorp is largely unmaintained. That said, there is also a large community around it. Can I suggest opening up development so that this community can continue to develop gorp? Perhaps a mail to go-nuts?

Alec

**Comment by chmac** [comment]
Is modl actively developed and maintained? Looks like it's been quiet since late October last year. Otherwise, it certainly sounds like a sensible direction for gorp to me.

**Comment by jmoiron** [comment]
I've been maintaining it when I have time.  There are a few open PRs that I'm going to take action on in the coming month.  I wouldn't mind adding official contributors to it (esp @sqs who has already contributed a lot), especially if the decision was made to mothball gorp.

However, I have to warn upfront that although Modl is a fork of Gorp, it wasn't forked in order to continue maintenance on Gorp.  The main goals were a cleanup of Gorp's API and an internal rewrite to base some of its database code on sqlx instead.  Part of this was that Gorp's original CRUD API (before @robfig's changes) was somewhat un-go-like (no pointer passing, so lots of casting), and part was that I wanted to test an assumption I had which was that sqlx was suitable as a substrate for other ORM designers and could allow them to skip reinventing db<->struct serialization.

So, while modl maintains a lot of the feel and structure of gorp, it does dispense with a few things that gorp does and it behaves slightly differently out of the box.  For a project starting out there's almost no difference;  if you're running something large in production there are behavioral differences which the compiler will not notify you about, and some things (purposefully) missing from it that some Gorp users might potentially rely on.

**Comment by franklinwise** [comment]
Yeah, merging the two products doesn't seem like the right approach, since they are based on fundamentally different principles (and frameworks). Maybe move Gorp to an github organization, so coopernurse can control rights for commiters and admins?

**Comment by coopernurse** [comment]
@GeertJohan has kindly created an organization (go-gorp) so I'm considering moving this repo there.  

Any other opinions on this before I do that?  Seems like the right solution.

**Comment by GeertJohan** [comment]
I now also see that merging modl and gorp isn't as smart as I initially thought. Although gorp could possibly benefit from some improvements made in modl, I think the main/first goal for the go-gorp organization should be addressing the existing/open issues and PR's.

I've asked @coopernurse to fork go-gorp/gorp back to coopernurse/gorp (if it gets moved), so existing users' code won't break. I've named the organization go-gorp so it is compatible with gopkg.in, but whether or not (and how) to use gopkg.in should first be discussed openly.

**Comment by GeertJohan** [comment]
Also, to be clear: I don't plan to maintain gorp all by myself. I believe it would be best to have multiple maintainers in the go-gorp organization.

**Comment by GeertJohan** [comment]
@begizi @benprew 
Are you still interested in helping with maintaining this project?

**Comment by begizi** [comment]
@GeertJohan I'd love to help out in any way I can. As mentioned above, I am very new to go and have only been using it for a few months. I do love gorp though and have used it in a couple of my projects so I'm all for helping improve it with some needed bug fixes and enhancements.

**Comment by sqdk** [comment]
@GeertJohan I'm actively using gorp at work and would love to help maintain the project. I am not terribly experienced, but i'll be happy to help where ever i can.

**Comment by GeertJohan** [comment]
Great, I'll email you both.

**Comment by benprew** [comment]
I use gorp at work too and would be happy to help maintain it.

Thanks

**Comment by GeertJohan** [comment]
We've moved the repository and new maintainers have been added.
A development mailing list has been opened at https://groups.google.com/forum/#!forum/gorp-dev

**Comment by mhkt** [comment]
i think you invited the wrong person.

On Sat, Jan 31, 2015 at 3:13 PM, Geert-Johan Riemer <
notifications@github.com> wrote:

> Closed #211 <https://github.com/go-gorp/gorp/issues/211>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/go-gorp/gorp/issues/211#event-228033428>.
>



-- 
Matt Hartman | @matthartman <http://twitter.com/matthartman>
director of seed investments
betaworks

*...join openbeta <http://www.betaworks.com/openbeta> for early access to
our newest products*

**Comment by GeertJohan** [comment]
@mhkt What do you mean? I just checked the audit logs for go-gorp and could not find any unintended invites.

**Comment by matthartman** [comment]
nevermind -- this is matt hartman (matt@betaworks.com now goes to me) but
matt hackett is working on changing the email i think.

On Mon, Feb 2, 2015 at 10:46 AM, Geert-Johan Riemer <
notifications@github.com> wrote:

> @mhkt <https://github.com/mhkt> What do you mean? I just checked the
> audit logs for go-gorp and could not find any unintended invites.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/go-gorp/gorp/issues/211#issuecomment-72479029>.
>



-- 
Matt Hartman // @matthartman <http://twitter.com/matthartman> // blog at
hrt.mn
