### ISSUE TITLE
How to access gorp in non controller package?

### ISSUE THREAD

**Issue by goors** [go-gorp/gorp#262]
I want to access gorp.Transaction from some helper method. I am using revel. For example:
<pre>
type Helper struct {
	Txn *gorp.Transaction
}
func (h Helper) GetUserById(id int64) *models.User{
	p, err := h.Txn.Get(models.User{}, id)
	if err != nil || p == nil {
		return nil
	}
	return p.(*models.User)
}
</pre>
but that shows me and error: runtime error: <b>invalid memory address or nil pointer dereference</b>
when I call this from controller with: return helpers.GetUserById{}.GetUserById(id)

Any answer is appreciated or I will have to pass gorp.Transaction from controller methods to helper methods (just stupid way to solve this).

<b>Update</b>
This is working like this:
<pre>
//in helper
type Helper struct {
    Txn *gorp.Transaction
}
func (h Helper) GetUserById(id int64) *models.User{
    p, err := h.Txn.Get(models.User{}, id)
    if err != nil || p == nil {
        return nil
    }
    return p.(*models.User)
}
//in controller
h := helpers.Helper{a.Txn}
return h.GetuserById(id)
</pre>

but I am not sure if this is a correct way.
There is so little go docs that I am really not sure what is wrong and what is right.

**Comment by nelsam** [comment]
@goors : Your update certainly works, and it's not a bad solution.  You could also make `helpers.New(tx *gorp.Transaction)` as a constructor for your helper type.

However, remember that Go isn't an object-oriented language, so it doesn't *always* make sense to make a type just for some methods.  For example, instead of your `GetUserById` logic being a method on a struct, it *might* make sense to move it to a function:

```go
//in helper
// Note: "tx *gorp.Transaction" could be rewriten "exec gorp.SqlExecutor" if you don't need to
// restrict UserById to execute only on transactions.
func UserById(tx *gorp.Transaction, id int64) *models.User{
    p, err := tx.Get(models.User{}, id)
    if err != nil || p == nil {
        return nil
    }
    return p.(*models.User)
}
//in controller
return helpers.UserById(id)
```

However, I have no knowledge of other things your helper is doing, so I don't know if that's necessarily correct for your use case.

**Comment by goors** [comment]
I have in User helper multiple methods such as UserById, UserByEmail, Users, UpdateUser, DeleteUser
and they all use struct Helper. Can you tell me if my approach is ok with multiple methods using same struct or?

**Comment by nelsam** [comment]
That sounds fine.  It's always a game of weighing lines of code against ease of understanding - do whatever reads easiest/cleanest to you.

As far as what reads cleanly to me (these are personal preferences, mostly, so I'm not trying to claim that you should follow them):

1. `Get` is kinda unnecessary in the function/method name, to my mind.  It's implied by the fact that the function returns a value.
  1. I like to look at the full function signature.  If the function name is repeating information I already know from the parameters or return values, it's not really necessary in the name.
  2. There are exceptions.  For example, with `UserByID` and `UserByEmail`, they need to be named two different things.  So even though the function signature makes it obvious that they're querying by ID and email (respectively), it makes sense to include that in the function name, too.
2. If you use `golint`, it will complain if you use `Id` instead of `ID`.
3. I kinda like providing a "constructor", because `helpers.New(tx)` reads cleaner to me than `helpers.Helper{tx}`.

I'm going to close this issue, since you've gotten your code working.
