### ISSUE TITLE
Ignoring columns not mapped to struct fields

### ISSUE THREAD

**Issue by a13xb** [go-gorp/gorp#281]
I am investigating whether to adopt gorp, and ran into the following problem: if I add a new column to the database, gorp will fail to do a `Get()` or `select *` from this table. From what I can see, there seems to be no way to ignore new columns if they don't map to a struct field.

**Why I want to do this:** the way we usually do it is by applying schema changes before rolling out new application code. Old app can run on new schema, it simply ignores new columns. This allows application updates with zero downtime (and I can run old version in parallel).

So, the question is whether I'm missing something and it's, in fact, possible with gorp. If not, would you consider adding it or accepting a patch?

**Comment by nelsam** [comment]
`Get()` should *only* care about fields that are mapped to a struct.  The select statement generated will handle all columns the struct defines, but no more.  If `Get()` is causing problems with new columns that aren't mapped yet, then that's a bug.

For `select *`, the bug is not in gorp, it's in `select *`.  Put simply, `select *` is code smell - don't do it.  Your code should be selecting columns explicitly, either directly via select strings or via some library that generates a select statement from your struct.

For generating a select statement, you can check out [gorq (I wrote it, so grain of salt and all that)](https://github.com/nelsam/gorq)(and I haven't gotten a chance to figure out why the build has started failing, but it is still working quite well for production code) or [squirrel](https://github.com/lann/squirrel), or just make use of `dbmap.TableFor` and `table.Columns` to add column names to your query.

**Comment by a13xb** [comment]
@nelsam

> `Get()` should only care about fields that are mapped to a struct.

Right, I have probably misremembered.

> Put simply, `select *` is code smell - don't do it.

Let's agree to disagree here. I find it perfectly acceptable. From the perspective of my code, there is no practical difference between "explicit list of all columns in a table" vs "`*` + ignoring unknown columns".

> For generating a select statement, you can check out `gorq` [...]

Yes, failing build and a big warning on top doesn't fill me with confidence. :)
Ideally, I'd prefer not to bring an extra 3rd party library, if possible, although I'm not completely against it, if there is no other alternative. Thanks for the suggestions.

**Comment by a13xb** [comment]
`dbmap.TableFor` + `table.Columns` did the trick. :+1:
Could be a candidate for a utility function, as it's mostly a just copy of [`bindGet`](https://github.com/go-gorp/gorp/blob/master/table_bindings.go#L267).

**Comment by nelsam** [comment]
When I say "code smell," I don't mean inherently evil; it just *suggests* that you'll have issues down the road.  So while I'm sure it's fine now, I still recommend doing your best to avoid it.  :)

I contracted as a DBA for a while (and I've kept up with it, sorta - which is why I wrote gorq); in all of the cases that I've seen, `select *` is a bad idea in the long run.  It may not make a difference to you now, but having seen both applications that use `select *` and those that don't 10 years down the road (when they finally shell out for a DBA contractor), the ones that are more explicit about column mappings are much easier to maintain.

If you're happy with the solution you've found, please close the ticket.

**Comment by a13xb** [comment]
This code will likely be gone in 10 years (famous last words).

**Comment by a13xb** [comment]
Well, burn on me!

Not a week later got bitten by [a bug/feature in sqlstruct](https://github.com/kisielk/sqlstruct/issues/8), where unmapped `time.Time` fields [get scanned into `sql.RawBytes` sink](https://github.com/kisielk/sqlstruct/blob/95b95639239be07d091748628808b8e364e505e7/sqlstruct.go#L253), which fails if the value is not `nil`. Although, sqlstruct should handle it, the situation could have been avoided if I selected fields explicitly.

**Comment by wz2b** [comment]
> > Put simply, `select *` is code smell - don't do it.
> Let's agree to disagree here. I find it perfectly acceptable. From the perspective of my code, there is no practical difference between "explicit list of all columns in a struct" vs "`*` + ignoring unknown columns".

I would in general find this comment - put in a positive tone as "be explicit" - compelling.  But if you have a large number of fields, I would have to say "it depends."  If you have a decorated struct with a lot of objects, then you ALSO have to write a huge query, naming every field, to select on it (maybe also with some other clauses like LIMIT), then I think that's 1) far more repetition 2) more likely to fail.

In particular, right now if you have an excess field gorp just panics.  To me that's far too strict.  The extra field _might_ indicate that you have some kind of problem - like a mismatched decoration/column name - but there has to be a better way to handle that than just panicking.
