### ISSUE TITLE
selectVal appears to mask possible sql.Row errors

### ISSUE THREAD

**Issue by rolandshoemaker** [go-gorp/gorp#364]
[`selectVal`](https://github.com/go-gorp/gorp/blob/c5fd513e7b0a246178d6eb97c6cfe334b7e96afc/select.go#L156) appears to throw away possible `sql.Row` errors when [no rows are returned and masks them](https://github.com/go-gorp/gorp/blob/c5fd513e7b0a246178d6eb97c6cfe334b7e96afc/select.go#L171-L173) with `sql.ErrNoRows`.

It seems like this block should contain a check for this, i.e. `if err := rows.Err(); err != nil { return err }`.

**Comment by nelsam** [comment]
That seems likely based on the docs.  Do you have an idea of a test case we could implement that would expose the problem?

**Comment by jsha** [comment]
We're seeing errors that are very likely caused by this (probable) bug in our production environment, but we've tried to produce a minimized test case and are pretty stumped. Below is an example program that reproduces pretty closely the setup we use in production, including in particular max_statement_time, ReadTimeout, WriteTimeout, and Timeout. However, this program correctly prints

```
Error 1969: Query execution was interrupted (max_statement_time exceeded)
```

Rather than `sql: no rows` as we see in our production logs. Maybe the particular conditions are rare, and depend on a timeout occurring between getting notification that the query is ready, and fetching the first result?

```
package main

import (
	"database/sql"
	"log"
	"time"

	mysql "github.com/go-sql-driver/mysql"
	"gopkg.in/gorp.v1"
)

func main() {
	config, err := mysql.ParseDSN("root@tcp(boulder-mysql:3306)/boulder_sa_integration")
	if err != nil {
		log.Fatal(err)
	}
	config.ReadTimeout = 5 * time.Second
	config.WriteTimeout = 5 * time.Second
	config.Timeout = 100 * time.Millisecond
	config.Params = make(map[string]string)
	config.Params["max_statement_time"] = "4.75"
        config.Params["sql_mode"] = "STRICT_ALL_TABLES"
	db, err := sql.Open("mysql", config.FormatDSN())
	if err != nil {
		log.Fatal(err)
	}

	// construct a gorp DbMap
	dbmap := &gorp.DbMap{
		Db:      db,
		Dialect: gorp.MySQLDialect{Engine: "InnoDB", Encoding: "UTF8"},
	}

	var count int
	err = dbmap.SelectOne(&count, `SELECT COUNT(1) FROM (SELECT SLEEP(1000) ) as t;`)
	if err != nil {
		log.Fatal(err)
	}
}
```

**Comment by jsha** [comment]
BTW, our evidence that this issue is surfacing for us in prod: We were using SelectOne with an unoptimized `SELECT COUNT(1) WHERE ... ` query that had to do a row scan over 200k rows (for one user), and were getting `sql: no rows in result set` on the result, even though there should always be a row because it's a count. We weren't getting the error for other users who had a smaller set of rows. When we deleted 95% of the rows for the affected user, their queries started completing normally again. So it really looks like that query was timing out, but giving us `sql: no rows` instead of the timeout error.
