### ISSUE TITLE
Embedded Time structs fail in PostgreSql

### ISSUE THREAD

**Issue by joeblubaugh** [go-gorp/gorp#86]
I have a data structure:

    type Times struct {
        One time.Time
        Two time.Time
    }

    type EmbeddedTime struct {
        Id string
        Times
    }

Using this structure I'm able to create a table and insert structs into it, but when calling get, I get an error:

[CreateDb] select "id","one","two" from "embeddedstruct" where "id"=$1; [[testId1]]
Error getting from db! sql: Scan error on column index 5: unsupported driver -> Scan pair: []uint8 -> *time.Time

This seems like an error in the SQL module or in the way that GORP represents these time fields to the Scanner..

**Comment by GeertJohan** [comment]
Better late then never (and because someone else might find this useful):

It looks like you are using `go-sql-mysql/mysql` and do not have the `parseTime` parameter set to true.
Please see: https://github.com/go-sql-driver/mysql/#parsetime

I assume this answers your question, if not: please re-open this issue.

**Comment by joeblubaugh** [comment]
@GeertJohan yep, that seems to do it. :sheep:
